In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
population_data = pd.read_csv("../data/raw/Population_data.csv")

In [3]:
#Seleccion de subconjunto de datos de estudio
Lista_paises =['Argentina','Brazil','Brunei Darussalam','Canada','Colombia','Croatia','Ecuador','Finland','Germany','Hungary','Israel','Japan','Kuwait','Mexico','Nicaragua','Singapore','Slovenia','Spain','Sweden','United States']
population_selected = population_data.loc[population_data['Country Name'].isin(Lista_paises)]
population_selected.reset_index(drop = True,inplace= True)

In [4]:
#Drops de columnas vacias o inservibles
before_1995 = population_selected.columns[range(4,28)]
after_2017 = population_selected.columns[range(51,len( population_selected.columns))]

population_first = population_selected.iloc[:,2:]
population_clean = population_first.drop(['Country Code'],axis = 1).drop(before_1995,axis = 1).drop(after_2017,axis = 1)

In [5]:
#Modificaci√≥n nombres columnas para cumplir un estandar
dic = {population_clean.columns.to_list()[0]:population_clean.columns.to_list()[0]}
columnas_nombres = population_clean.columns.to_list()
for i in range(1,len(columnas_nombres)):
    nombre = columnas_nombres[i]
    dic[columnas_nombres[i]] = str(nombre[:4])
population_clean.rename(columns = dic,inplace = True)

In [6]:
population_clean['Country Name'] =  ['Argentina','Brazil','Brunei Darussalam','Canada','Colombia','Croatia','Ecuador','Finland','Germany','Hungary','Israel','Japan','Kuwait','Mexico','Nicaragua','Singapore','Slovenia','Spain','Sweden','United States of America']

In [7]:
#Creacion columna sanidad
Sanidad = [0,0,1,1,0,0,0,1,1,0,1,1,1,0,0,1,1,1,1,0]
population_clean['Sanidad'] = Sanidad

In [8]:
population_clean

,Country Name,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,Sanidad
0,Argentina,34828170,35246374,35657429,36063459,36467218,36870787,37275652,37681749,38087868,38491972,38892931,39289878,39684295,40080160,40482788,40788453,41261490,41733271,42202935,42669500,43131966,43590368,44044811,0
1,Brazil,162019896,164614688,167209040,169785250,172318675,174790340,177196054,179537520,181809246,184006481,186127103,188167356,190130443,192030362,193886508,195713635,197514534,199287296,201035903,202763735,204471769,206163058,207833831,0
2,Brunei Darussalam,297114,304622,311958,319144,326210,333165,340034,346782,353293,359433,365114,370263,374965,379421,383906,388646,393688,398989,404421,409769,414907,419800,424473,1
3,Canada,29302311,29610218,29905948,30155173,30401286,30685730,31020902,31360079,31644028,31940655,32243753,32571174,32889025,33247118,33628895,34004889,34339328,34714222,35082954,35437435,35702908,36109487,36543321,1
4,Colombia,36421438,37076387,37723803,38364307,38999468,39629965,40255956,40875363,41483872,42075953,42647731,43200901,43737512,44254972,44750054,45222699,45662747,46075721,46495492,46967706,47520667,48175048,48909844,0
5,Croatia,4620030,4557097,4534920,4532135,4512597,4468302,4299642,4302174,4303399,4304600,4310145,4311159,4310217,4309705,4305181,4295427,4280622,4267558,4255689,4238389,4203604,4174349,4124531,0
6,Ecuador,11455204,11703174,11951452,12198449,12442115,12681123,12914667,13143465,13369678,13596388,13825847,14059384,14296557,14535739,14774424,15011117,15243883,15474102,15707474,15951838,16212020,16491115,16785361,0
7,Finland,5107790,5124573,5139835,5153498,5165474,5176209,5188008,5200598,5213014,5228172,5246096,5266268,5288720,5313399,5338871,5363352,5388272,5413971,5438972,5461512,5479531,5495303,5508214,1
8,Germany,81678051,81914831,82034771,82047195,82100243,82211508,82349925,82488495,82534176,82516260,82469422,82376451,82266372,82110097,81902307,81776930,80274983,80425823,80645605,80982500,81686611,82348669,82657002,1
9,Hungary,10328965,10311238,10290486,10266570,10237530,10210971,10187576,10158608,10129552,10107146,10087065,10071370,10055780,10038188,10022650,10000023,9971727,9920362,9893082,9866468,9843028,9814023,9787966,0
10,Israel,5545000,5692000,5836000,5971000,6125000,6289000,6439000,6570000,6689700,6809000,6930100,7053700,7180100,7308800,7485600,7623600,7765800,7910500,8059500,8215700,8380100,8546000,8713300,1
11,Japan,125439000,125757000,126057000,126400000,126631000,126843000,127149000,127445000,127718000,127761000,127773000,127854000,128001000,128063000,128047000,128070000,127833000,127629000,127445000,127276000,127141000,126994511,126785797,1
12,Kuwait,1605901,1626857,1710256,1831119,1951636,2045123,2103282,2136997,2161626,2200492,2270198,2373672,2504019,2656009,2821045,2991884,3168060,3348853,3526376,3690941,3835591,3956875,4056099,1
13,Mexico,91663285,93147044,94611002,96056321,97484832,98899845,100298153,101684758,103081020,104514932,106005203,107560153,109170502,110815271,112463887,114092963,115695473,117274155,118827161,120355128,121858258,123333376,124777324,0
14,Nicaragua,4652185,4741578,4827661,4910647,4991040,5069302,5145366,5219328,5292118,5364935,5438690,5513763,5590055,5667432,5745526,5824065,5903039,5982526,6062454,6142733,6223240,6303974,6384855,0
15,Singapore,3524506,3670704,3796038,3927213,3958723,4027887,4138012,4175950,4114826,4166664,4265762,4401365,4588599,4839396,4987573,5076732,5183688,5312437,5399162,5469724,5535002,5607283,5612253,1
16,Slovenia,1989872,1988628,1985956,1981629,1983045,1988925,1992060,1994530,1995733,1997012,2000474,2006868,2018122,2021316,2039669,2048583,2052843,2057159,2059953,2061980,2063531,2065042,2066388,1
17,Spain,39724050,39889852,40057389,40223509,40386875,40567864,40850412,41431558,42187645,42921895,43653155,44397319,45226803,45954106,46362946,46576897,46742697,46773055,46620045,46480882,46444832,46484062,46593236,1
18,Sweden,8826939,8840998,8846062,8850974,8857874,8872109,8895960,8924958,8958229,8993531,9029572,9080505,9148092,9219637,9298515,9378126,9449213,9519374,9600379,9696110,9799186,9923085,10057698,1
19,United States of America,266278000,269394000,272657000,275854000,279040000,282162411,284968955,287625193,290107933,292805298,295516599,298379912,301231207,304093966,306771529,309321666,311556874,313830990,315993715,318301008,320635163,322941311,324985539,0

In [9]:
# Exportaci√≥n del dataset
#population_clean.to_csv("../data/clean/population_clean.csv")